name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download pkg
      run: |
        wget https://git.motis-project.de/dl/pkg/-/jobs/artifacts/master/raw/build/pkg?job=linux-release
        mv pkg\?job=linux-release pkg
        chmod +x pkg

    - name: Download dependencies
      run: ./pkg -l -h

    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ccache
        key: ccache-${{ hashFiles('**/*.h') }}-${{ hashFiles('**/*.cc') }}

    - name: Pull Docker image
      run: docker pull motisproject/cpp-build:latest

    - name: Build
      run: |
        docker run \
          -v "$PWD:/repo" \
          -e CCACHE_DIR=/repo/ccache \
          --rm motisproject/cpp-build:latest \
          bash -c "ccache -z && cmake-ccache-gcc-9 /repo && ninja utl-test && ccache -s && cp utl-test /repo"

    - name: Run Tests
      run: ./utl-test
